name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up build args
      run: |
        echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${GITHUB_REF_NAME%-*}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        provenance: false
        tags: |
          ghcr.io/vergilgao/telecom-iptv-mock:${{ env.MAJOR_VERSION }}
          ghcr.io/vergilgao/telecom-iptv-mock:${{ env.MINOR_VERSION }}
          ghcr.io/vergilgao/telecom-iptv-mock:${{ env.BUILD_VERSION }}
          ghcr.io/vergilgao/telecom-iptv-mock:${{ env.TAG_VERSION }}
          ghcr.io/vergilgao/telecom-iptv-mock:latest

    - name: purge packages
      uses: dylanratcliffe/delete-untagged-containers@main
      with:
        package_name: telecom-iptv-mock
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}